// <auto-generated />
using ManageDb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace ManageDb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.17");

            modelBuilder.Entity("ManageDb.Models.TNVEDCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TNVEDCodes");
                });

            modelBuilder.Entity("ManageDb.Models.TechReg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TechRegs");
                });

            modelBuilder.Entity("TNVEDCodeTechReg", b =>
                {
                    b.Property<int>("TNVEDCodesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TechRegsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TNVEDCodesId", "TechRegsId");

                    b.HasIndex("TechRegsId");

                    b.ToTable("TNVEDCodeTechReg");
                });

            modelBuilder.Entity("TNVEDCodeTechReg", b =>
                {
                    b.HasOne("ManageDb.Models.TNVEDCode", null)
                        .WithMany()
                        .HasForeignKey("TNVEDCodesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManageDb.Models.TechReg", null)
                        .WithMany()
                        .HasForeignKey("TechRegsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
